### ISSUE TITLE
Puma 6 support

### ISSUE THREAD

**Issue by severinkaelin** [harmjanblok/puma-metrics#42]
Hello
First of all, thanks for the great gem.

There seem to be compatibility issues with the latest version of the gem (1.2.5) and the latest version of puma (6.0.0).

Gemfile.lock:
````ruby
puma (6.0.0)
  nio4r (~> 2.0)
puma-metrics (1.2.5)
  prometheus-client (>= 0.10)
  puma (>= 5.0)
````

config/puma.rb:

````ruby
...
# Allow puma to be restarted by `bin/rails restart` command.
plugin :tmp_restart
plugin 'metrics'
````

Attempt to start the rails server / puma (`rails s`):

````ruby
severin@ws:~/dev/HelloWorld$ rails s
=> Booting Puma
=> Rails 7.0.4 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
/home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-metrics-1.2.5/lib/puma/plugin/metrics.rb:16:in `start': undefined method `min_threads=' for #<Puma::Server:0x00007feb3ee15c40...
````

```ruby
    metrics.min_threads = 0
           ^^^^^^^^^^^^^^
Did you mean?  min_threads
               max_threads
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/plugin.rb:24:in `block in fire_starts'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/plugin.rb:22:in `each'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/plugin.rb:22:in `fire_starts'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/puma/launcher.rb:179:in `run'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/puma-6.0.0/lib/rack/handler/puma.rb:72:in `run'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/server.rb:327:in `start'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:38:in `start'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:143:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/severin/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```

***

See details about the Puma 6 upgrade: https://github.com/puma/puma/blob/master/6.0-Upgrade.md#upgrade

> 4. We've removed the following public methods on Puma::Server: Puma::Server#min_threads, Puma::Server#max_threads. Instead, you can pass in configuration as an option to Puma::Server#new. This might make certain gems break (capybara for example).

**Comment by harmjanblok** [comment]
@severinkaelin thanks for your work on #43, as that PR is now merged I assume this issue can be considered done.

**Comment by severinkaelin** [comment]
@harmjanblok Yes, make sense to close this issue. Thank you for the quick feedback during development and the prompt release afterwards.
